[package]
name = "cme"
version = "0.1.2"
edition = "2024"
description = "Checkmate Embedding: the embedded specification for the Checkmate scripting language."
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/checkmatelang/checkmate"
keywords = ["checkmate", "scripting", "embedding", "language"]
categories = ["development-tools"]
