[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
version = "0.2.0"
edition = "2024"
authors = ["Matin Mohammadi"]
license = "Apache-2.0"
description = "Checkmate Engine: A statically typed, embeddable scripting language"
readme = "README.md"
repository = "https://github.com/cmengine/checkmate"
keywords = ["checkmate", "scripting", "embedding", "language"]
categories = ["compilers", "parser-implementations"]

[package]
name = "cme"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description.workspace = true
readme.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
publish = true

[dependencies]
cme-core = { path = "crates/cme-core", version = "0.2.0", optional = true }
cme-compiler = { path = "crates/cme-compiler", version = "0.2.0", optional = true }
cme-interp = { path = "crates/cme-interp", version = "0.2.0", optional = true }
cme-runtime = { path = "crates/cme-runtime", version = "0.2.0", optional = true }

[features]
default = []
core = ["dep:cme-core"]
compiler = ["dep:cme-compiler"]
interp = ["dep:cme-interp"]
runtime = ["dep:cme-runtime"]
# The CLI toolchain requires these crates to function
cli = ["core", "compiler", "interp", "runtime"]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(feature, values(\"all\"))"] }
