[package]
name = "cme-lsp"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description.workspace = true
readme.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
publish = true

[dependencies]
cme-core = { path = "../cme-core", version = "0.2.0" }
cme-compiler = { path = "../cme-compiler", version = "0.2.0" }
tower-lsp-server = "0.23.0"
salsa = "0.28.2"
tokio = { version = "1", features = ["rt", "io-util", "io-std", "macros", "time"] }

[dev-dependencies]
futures = { version = "0.3", default-features = false, features = ["std"] }
serde_json = "1"
tower = { version = "0.5", features = ["util"] }
