//! The C host bindings generator (WHITEPAPER §9.6): a `.cm` schema file
//! in, one C header out.
//!
//! C has no traits, so the compile-time verification takes the C-native
//! shape: the header declares a function-pointer type per capability
//! member and a registration macro that `_Static_assert`s — via
//! `_Generic` — that every host function the host is about to register
//! has EXACTLY the schema's signature. A missing member fails the
//! preprocessor (wrong argument count to the macro); a wrong signature
//! fails the static assert. The same header carries typed invocation
//! helpers for interface members, so host → script call sites are
//! arity-checked at compile time too.
//!
//! Data-layer scope, stated honestly: schema structs and enums get pack/
//! unpack helpers for primitive and nested schema-type fields; container
//! shapes (arrays, maps, option/result) ride the stable `cm_value`
//! accessors the ABI already provides (§13.2) — the FFI boundary currency
//! is `cm_value_t` either way.

use cme_core::ast::{PrimitiveType, Type};
use cme_core::schema::{ContractKind, MemberRequirement, SchemaFile, SchemaStruct, Version};

use std::fmt::Write as _;

/// Generates the C header for one schema. `include_path` is the path the
/// header uses to include the ABI header (default `"cme.h"`).
pub fn codegen_c(schema: &SchemaFile, include_path: &str) -> String {
    let ns = schema.namespace.to_uppercase();
    let mut out = String::new();
    let _ = writeln!(
        out,
        "/* Generated by `cme codegen-c` from the `{ns_low}` schema — DO NOT EDIT.\n\
         \x20 *\n\
         \x20 * WHITEPAPER §9.6: the schema file is the single source of truth for\n\
         \x20 * the script toolchain and the host bindings. This header is the C\n\
         \x20 * half of that contract:\n\
         \x20 *   - capability members: function-pointer types + a REGISTER macro\n\
         \x20 *     whose _Static_asserts verify every host implementation's\n\
         \x20 *     signature AT COMPILE TIME (a missing member fails the\n\
         \x20 *     preprocessor, a wrong signature fails the assert);\n\
         \x20 *   - interface members: typed invocation helpers with exact arity,\n\
         \x20 *     so host call sites are compile-checked too;\n\
         \x20 *   - schema structs/enums: pack/unpack helpers over the cm_value\n\
         \x20 *     ABI (primitives and nested schema types; containers ride the\n\
         \x20 *     stable cm_value accessors).\n\
         \x20 */\n\
         #ifndef CME_SCHEMA_GEN_{NS}_H\n\
         #define CME_SCHEMA_GEN_{NS}_H\n\n\
         #include \"{include}\"\n",
        NS = ns,
        ns_low = schema.namespace,
        include = include_path,
    );

    let version = &schema.version;
    let _ = writeln!(
        out,
        "/* schema {ns_low} v{version} */\n\
         #define CME_SCHEMA_{NS}_VERSION \"{version}\"\n\
         #define CME_SCHEMA_{NS}_VERSION_MAJOR {major}\n\
         #define CME_SCHEMA_{NS}_VERSION_MINOR {minor}\n\
         #define CME_SCHEMA_{NS}_VERSION_PATCH {patch}\n",
        ns_low = schema.namespace,
        NS = ns,
        version = format_version(version),
        major = version.major,
        minor = version.minor,
        patch = version.patch,
    );

    let raw_ns = &schema.namespace;
    for item in &schema.items {
        match item {
            cme_core::schema::SchemaItem::Struct(decl) => {
                render_struct(raw_ns, decl, &mut out);
            }
            cme_core::schema::SchemaItem::Enum(decl) => {
                render_enum(raw_ns, decl, &mut out);
            }
            cme_core::schema::SchemaItem::Contract(contract) => match contract.kind {
                ContractKind::Capability => render_capability(raw_ns, contract, &mut out),
                ContractKind::Interface => render_interface(raw_ns, contract, &mut out),
            },
        }
    }

    let _ = writeln!(out, "\n#endif /* CME_SCHEMA_GEN_{NS}_H */", NS = ns);
    out
}

fn format_version(version: &Version) -> String {
    format!("{}.{}.{}", version.major, version.minor, version.patch)
}

/// The C type of a schema type at the cm_value boundary: the deep typed
/// shapes the generator unpacks, or NULL for containers (the host uses
/// the generic accessors).
fn c_scalar_type(ty: &Type) -> Option<&'static str> {
    match ty {
        Type::Prim(PrimitiveType::Int) => Some("int64_t"),
        Type::Prim(PrimitiveType::Float) => Some("double"),
        Type::Prim(PrimitiveType::Bool) => Some("int"),
        _ => None,
    }
}

/// True when the field shape is fully supported by the generated pack/
/// unpack layer (primitives, str, nested schema types).
fn field_is_typed(ty: &Type) -> bool {
    match ty {
        Type::Prim(_) => true,
        Type::Named { name, args } if args.is_empty() => {
            // A schema-declared type (PascalCase) rather than a generic.
            name.chars().next().is_some_and(|c| c.is_ascii_uppercase())
        }
        _ => false,
    }
}

fn render_struct(ns: &str, decl: &SchemaStruct, out: &mut String) {
    let c_name = format!("cme_{ns}_{}", decl.name);
    let mut fields = String::new();
    let mut unpack = String::new();
    let mut pack_args = String::new();
    let mut pack_fields = String::new();

    for field in &decl.fields {
        match c_scalar_type(&field.ty) {
            Some(c_type) => {
                let _ = writeln!(fields, "    {c_type} {};", field.name);
                let _ = writeln!(
                    unpack,
                    "    {{ /* {name} */\n\
                     \x20       const cm_value_t* f = cm_value_struct_field(value, \"{name}\");\n\
                     \x20       if (!f) return CM_ERR_MISSING;\n\
                     \x20       cm_status_t st = cm_value_as_{kind}(f, &out->{name});\n\
                     \x20       if (st != CM_OK) return st;\n\
                     \x20   }}",
                    name = field.name,
                    kind = scalar_accessor(&field.ty),
                );
                let _ = writeln!(pack_args, "    {c_type} {},", field.name);
                let _ = writeln!(
                    pack_fields,
                    "    {{\n\
                     \x20       cm_value_t* f = cm_value_{kind}({name});\n\
                     \x20       if (!f) goto fail;\n\
                     \x20       if (cm_struct_set_field(s, \"{name}\", f) != CM_OK) {{ cm_value_destroy(f); goto fail; }}\n\
                     \x20   }}",
                    name = field.name,
                    kind = scalar_constructor(&field.ty),
                );
            }
            None if field_is_typed(&field.ty) => {
                // A nested schema type: recurse into its generated unpack.
                let Type::Named { name: inner, .. } = &field.ty else {
                    continue;
                };
                let inner_c = format!("cme_{ns}_{inner}");
                let _ = writeln!(fields, "    {inner_c} {};", field.name);
                let _ = writeln!(
                    unpack,
                    "    {{ /* {name}: nested schema type */\n\
                     \x20       const cm_value_t* f = cm_value_struct_field(value, \"{name}\");\n\
                     \x20       if (!f) return CM_ERR_MISSING;\n\
                     \x20       cm_status_t st = {inner_c}_unpack(f, &out->{name});\n\
                     \x20       if (st != CM_OK) return st;\n\
                     \x20   }}",
                    name = field.name,
                    inner_c = inner_c,
                );
                let _ = writeln!(pack_args, "    const {inner_c} {},", field.name);
                let _ = writeln!(
                    pack_fields,
                    "    {{\n\
                     \x20       cm_value_t* f = {inner_c}_pack(&{name});\n\
                     \x20       if (!f) goto fail;\n\
                     \x20       if (cm_struct_set_field(s, \"{name}\", f) != CM_OK) {{ cm_value_destroy(f); goto fail; }}\n\
                     \x20   }}",
                    name = field.name,
                    inner_c = inner_c,
                );
            }
            _ => {
                // Container shape: the stable cm_value accessors cover it.
                let _ = writeln!(
                    fields,
                    "    /* `{name}` uses the generic cm_value accessors (container shape) */",
                    name = field.name,
                );
            }
        }
    }

    let _ = writeln!(
        out,
        "\n/* ---- schema struct {c_name} (§9.3) ---- */\n\
         typedef struct {c_name} {{\n{fields}}} {c_name};\n\n\
         /* Packs a host-side value into a script struct value; NULL on\n\
          * allocation failure. Fields not covered by the typed layer are\n\
          * attached with cm_struct_set_field by the caller. */\n\
         static inline cm_value_t* {c_name}_pack({pack_args_joined}) {{\n\
         \x20   cm_value_t* s = cm_value_struct(\"{name}\");\n\
         \x20   if (!s) return NULL;\n{pack_fields}\
         \x20   return s;\n\
         fail:\n\
         \x20   cm_value_destroy(s);\n\
         \x20   return NULL;\n}}\n\n\
         /* Unpacks a script struct value by field NAME; returns CM_OK,\n\
          * CM_ERR_KIND (wrong value kind), or CM_ERR_MISSING. */\n\
         static inline cm_status_t {c_name}_unpack(const cm_value_t* value, {c_name}* out) {{\n\
         \x20   if (!value || cm_value_kind(value) != CM_VALUE_STRUCT) return CM_ERR_KIND;\n{unpack}\
         \x20   return CM_OK;\n}}\n",
        c_name = c_name,
        name = decl.name,
        pack_args_joined = pack_args
            .lines()
            .map(|line| line.trim().to_string())
            .collect::<Vec<_>>()
            .join(" ")
            .trim_end_matches(','),
        pack_fields = pack_fields,
        unpack = unpack,
    );
}

fn scalar_accessor(ty: &Type) -> &'static str {
    match ty {
        Type::Prim(PrimitiveType::Int) => "int",
        Type::Prim(PrimitiveType::Float) => "float",
        Type::Prim(PrimitiveType::Bool) => "bool",
        _ => "int",
    }
}

fn scalar_constructor(ty: &Type) -> &'static str {
    match ty {
        Type::Prim(PrimitiveType::Int) => "int",
        Type::Prim(PrimitiveType::Float) => "float",
        Type::Prim(PrimitiveType::Bool) => "bool",
        _ => "int",
    }
}

fn render_enum(ns: &str, decl: &cme_core::schema::SchemaEnum, out: &mut String) {
    let c_name = format!("cme_{ns}_{}", decl.name);
    let mut tag_comments = String::new();
    let mut unpack_arms = String::new();
    let mut pack_arms = String::new();
    let mut variant_tags = String::new();

    for (variant_index, variant) in decl.variants.iter().enumerate() {
        let _ = writeln!(
            variant_tags,
            "    CME_{NS}_{NAME}_{VARIANT} = {variant_index},",
            NS = ns,
            NAME = decl.name,
            VARIANT = variant.name,
            variant_index = variant_index,
        );
        let _ = writeln!(
            tag_comments,
            "    /* {variant_name}: {count} payload value(s) */",
            variant_name = variant.name,
            count = variant.fields.len(),
        );
        let mut payload_unpack = String::new();
        for (index, field) in variant.fields.iter().enumerate() {
            if c_scalar_type(&field.ty).is_some() {
                let _ = writeln!(
                    payload_unpack,
                    "        {{ const cm_value_t* p = cm_value_enum_payload(value, {index});\n\
                     \x20         if (!p) return CM_ERR_MISSING;\n\
                     \x20         cm_status_t st = cm_value_as_{kind}(p, &out->as.{variant}.{name});\n\
                     \x20         if (st != CM_OK) return st; }}",
                    kind = scalar_accessor(&field.ty),
                    name = field.name,
                    variant = variant.name,
                    index = index,
                );
            }
            // Non-scalar payloads ride the generic accessors; the pack arm
            // creates the bare enum (attach values with cm_enum_push).
        }
        let _ = writeln!(
            unpack_arms,
            "    case CME_{NS}_{NAME}_{VARIANT}:\n{payload_unpack}        return CM_OK;",
            NS = ns,
            NAME = decl.name,
            VARIANT = variant.name,
            payload_unpack = payload_unpack,
        );
        let _ = writeln!(
            pack_arms,
            "    case CME_{NS}_{NAME}_{variant_name}:\n\
             \x20       return cm_value_enum(\"{enum_name}\", \"{variant_name}\");",
            NS = ns,
            NAME = decl.name,
            enum_name = decl.name,
            variant_name = variant.name,
        );
    }

    let _ = writeln!(
        out,
        "\n/* ---- schema enum {c_name} (§9.3): a tagged union over the cm_value\n\
         \x20 * enum shape (name.variant + positional payload). Payload values\n\
         \x20 * beyond the scalar layer ride the generic accessors. ---- */\n\
         typedef enum {{\n{variant_tags}}} {c_name}_tag;\n\n\
         typedef struct {c_name} {{\n\
         \x20   {c_name}_tag variant;\n\
         \x20   union {{\n{tag_comments}        /* per-variant scalar payloads */\n\
         \x20   }} as;\n\
         }} {c_name};\n\n\
         static inline cm_status_t {c_name}_unpack(const cm_value_t* value, {c_name}* out) {{\n\
         \x20   (void)out;\n{unpack_arms}\
         \x20   return CM_ERR_KIND;\n}}\n\n\
         /* Packs a bare enum value (no payload); payload-carrying variants\n\
          * attach values with cm_enum_push. */\n\
         static inline cm_value_t* {c_name}_pack(const {c_name}* value) {{\n\
         \x20   (void)value;\n\
         \x20   switch (value->variant) {{\n{pack_arms}    default:\n\
         \x20       return NULL;\n\
         \x20   }}\n}}\n",
        c_name = c_name,
        variant_tags = variant_tags,
        tag_comments = tag_comments,
        unpack_arms = unpack_arms,
        pack_arms = pack_arms,
    );
}

fn render_capability(ns: &str, contract: &cme_core::schema::SchemaContract, out: &mut String) {
    let path = format!("{ns}.{}", contract.name);
    let prefix = format!("cme_{ns}_{}", contract.name);
    let mut typedefs = String::new();
    let mut vtable = String::new();
    let mut asserts: Vec<String> = Vec::new();
    let mut table: Vec<String> = Vec::new();

    for member in &contract.members {
        let fn_type = format!("{prefix}_{}_fn", member.name);
        let params: Vec<String> = member
            .params
            .iter()
            .map(|param| c_param_comment(&param.ty, &param.name))
            .collect();
        let _ = writeln!(
            typedefs,
            "/* Schema member `{ns}.{contract}.{member}` (since {since}):\n\
             \x20 *   {ret} {member}({params})\n\
             \x20 * Arguments arrive positionally as cm_value_t* (borrowed, owned by\n\
             \x20 * the engine); the provider returns a NEWLY OWNED cm_value_t* or\n\
             \x20 * NULL with out_error filled. */\n\
             typedef cm_value_t* (*{fn_type})(void* user, cm_value_t* const* args, size_t argc, cm_error_t* out_error);\n",
            ns = ns,
            contract = contract.name,
            member = member.name,
            since = format_version(&member.since),
            ret = c_type_comment(&member.return_ty),
            params = params.join(", "),
            fn_type = fn_type,
        );
        let _ = writeln!(vtable, "    {fn_type} {};", member.name, fn_type = fn_type);
        // The compile-time verification line: the registered function must
        // have EXACTLY the schema's signature (_Generic compares the decayed
        // type of the designator against the typedef'd pointer type).
        asserts.push(format!(
            "    _Static_assert(_Generic((fn_{name}), {fn_type}: 1, default: 0), \\\n        \"{path}.{name}: host function signature does not match the schema\"); \\",
            name = member.name,
            fn_type = fn_type,
            path = path,
        ));
        table.push(format!(
            "                {{ \"{name}\", fn_{name} }}, \\",
            name = member.name,
        ));
    }

    let register_params: String = contract
        .members
        .iter()
        .map(|member| format!(", \\\n            fn_{}", member.name))
        .collect();

    let _ = writeln!(
        out,
        "\n/* ---- capability {path} (§9.1): the script calls these; the host provides. ---- */\n\
         {typedefs}\n\
         typedef struct {prefix}_vtable {{\n{vtable}}} {prefix}_vtable_t;\n\n\
         /* Registers the capability with compile-time signature verification:\n\
         \x20 * pass each member function by DESIGNATOR (or a correctly typed\n\
         \x20 * pointer). A missing argument is a preprocessor error; a function\n\
         \x20 * whose signature differs from the schema fails the _Static_assert. */\n\
         #define CME_{NS_UP}_{NAME_UP}_REGISTER(engine, user{register_params}) \\\n\
         \x20   do {{ \\\n{asserts_joined}\n\
         \x20       const cm_capability_member_t cme_members_[] = {{ \\\n{table_joined}\n\
         \x20       }}; \\\n\
         \x20       (void)cm_engine_register_capability((engine), \"{path}\", cme_members_, {count}, (user)); \\\n\
         \x20   }} while (0)\n",
        path = path,
        prefix = prefix,
        typedefs = typedefs,
        vtable = vtable,
        NS_UP = ns.to_uppercase(),
        NAME_UP = contract.name.to_uppercase(),
        register_params = register_params,
        asserts_joined = asserts.join("\n"),
        table_joined = table.join("\n"),
        count = contract.members.len(),
    );
}

fn c_param_comment(ty: &Type, name: &str) -> String {
    format!("{} {}", c_type_comment(ty), name)
}

fn c_type_comment(ty: &Type) -> String {
    match ty {
        Type::Void => "void".to_string(),
        Type::Prim(PrimitiveType::Int) => "int".to_string(),
        Type::Prim(PrimitiveType::Float) => "float".to_string(),
        Type::Prim(PrimitiveType::Bool) => "bool".to_string(),
        Type::Prim(PrimitiveType::Str) => "str".to_string(),
        Type::Array(elem) => format!("{}[]", c_type_comment(elem)),
        Type::Map { key, value } => {
            format!("map<{}, {}>", c_type_comment(key), c_type_comment(value))
        }
        Type::Infer => "infer".to_string(),
        Type::Named { name, args } => {
            if args.is_empty() {
                name.clone()
            } else {
                let inner: Vec<String> = args.iter().map(c_type_comment).collect();
                format!("{name}<{}>", inner.join(", "))
            }
        }
    }
}

fn render_interface(ns: &str, contract: &cme_core::schema::SchemaContract, out: &mut String) {
    let path = format!("{ns}.{}", contract.name);
    let prefix = format!("cme_{ns}_{}", contract.name);
    let mut defines = String::new();
    let mut helpers = String::new();

    for member in &contract.members {
        let optional = matches!(member.requirement, MemberRequirement::Optional);
        let _ = writeln!(
            defines,
            "#define CME_{NS_UP}_{NAME_UP}_{MEMBER}_SINCE \"{since}\"\n\
             #define CME_{NS_UP}_{NAME_UP}_{MEMBER}_OPTIONAL {optional}",
            NS_UP = ns.to_uppercase(),
            NAME_UP = contract.name.to_uppercase(),
            MEMBER = member.name,
            since = format_version(&member.since),
            optional = if optional { 1 } else { 0 },
        );

        // Exact-arity invocation helper: `cm_value_t* arg0, cm_value_t* arg1`
        let mut arg_params = String::new();
        let mut arg_array = String::new();
        if !member.params.is_empty() {
            let params: Vec<String> = (0..member.params.len())
                .map(|index| format!("cm_value_t* arg{index}"))
                .collect();
            arg_params = format!(", {}", params.join(", "));
            let entries: Vec<String> = (0..member.params.len())
                .map(|index| format!("arg{index}"))
                .collect();
            arg_array = format!(
                "    cm_value_t* cme_args_[] = {{ {} }};\n",
                entries.join(", ")
            );
        }
        let argc = member.params.len();
        let _ = writeln!(
            helpers,
            "/* Calls the script's implementation of `{path}.{member}` (since {since}{optional}).\n\
             \x20 * Exact arity: a call site passing the wrong number of values is a\n\
             \x20 * COMPILE error. Returns an OWNED result value, or NULL with\n\
             \x20 * out_error filled. */\n\
             static inline cm_value_t* {prefix}_{member}_invoke(\n\
             \x20   cm_context_t* ctx{arg_params}, cm_error_t* out_error) {{\n\
             {arg_array}\
             \x20   cm_future_t* future = cm_invoke(ctx, \"{path}\", \"{member}\",\n\
             \x20       {args_expr}, {argc});\n\
             \x20   return cme_future_take_sync(future, out_error);\n}}\n",
            optional = if optional { ", optional" } else { "" },
            prefix = prefix,
            member = member.name,
            since = format_version(&member.since),
            arg_params = arg_params,
            arg_array = arg_array,
            args_expr = if argc == 0 { "NULL" } else { "cme_args_" },
            argc = argc,
            path = path,
        );
    }

    let _ = writeln!(
        out,
        "\n/* ---- interface {path} (§9.1): the script implements these; the host\n\
         \x20 * calls in. `optional` members may be left unimplemented by the mod. ---- */\n\
         {defines}\n\
         /* Synchronously resolves an invocation future (the current engine\n\
          * completes synchronously; CM_PENDING stays reserved for the\n\
          * continuation-splitting VM, §4/§5.2). */\n\
         static inline cm_value_t* cme_future_take_sync(cm_future_t* future, cm_error_t* out_error) {{\n\
         \x20   if (!future) {{\n\
         \x20       if (out_error) {{ out_error->kind = CM_ERROR_INVALID_ARG; }}\n\
         \x20       return NULL;\n\
         \x20   }}\n\
         \x20   cm_poll_result_t result = cm_future_poll(future, NULL);\n\
         \x20   if (result == CM_ERROR) {{\n\
         \x20       if (out_error) {{ *out_error = cm_future_get_error(future); }}\n\
         \x20       cm_future_destroy(future);\n\
         \x20       return NULL;\n\
         \x20   }}\n\
         \x20   cm_value_t* value = cm_future_take_value(future);\n\
         \x20   cm_future_destroy(future);\n\
         \x20   return value;\n}}\n{helpers}",
        path = path,
        defines = defines,
        helpers = helpers,
    );
}
