/* Schema-driven Checkmate embedding over a real multi-file MODULE, in C.
 *
 * This is the C twin of ../Rust/src/main.rs: same schema contract
 * (schemas/shop.cm), same module (shop_mod/), same expected results.
 *
 * Build and run from this directory with:
 *     make          # generates shop_schema_gen.h, builds ./shop_host
 *     ./shop_host shop_mod
 * Exit codes: 0 success, 1 runtime failure, 2 compile/usage failure.
 *
 * What this program proves, in order:
 *   1. `cme codegen-c` turns schemas/shop.cm into a C header at BUILD time
 *      (a Rust proc macro is not involved here; this is 100% the C half of
 *      the §9.6 contract, generated by the Checkmate toolchain itself).
 *   2. The host implements the capability with plain C functions, registers
 *      them through the GENERATED `CME_SHOP_STORE_REGISTER` macro (whose
 *      `_Static_assert`s verify every signature at COMPILE time), and loads
 *      the whole shop_mod/ MODULE through the schema gate.
 *   3. The host calls the script twice: `main` via raw `cm_invoke`
 *      (script calls back into the C providers), and `shop.checkout` via
 *      the GENERATED exact-arity helpers (typed C -> script).
 *
 * Ownership rules (the whole C API hangs on these; see cme.h):
 *   - Constructors (`cm_value_int`, generated `_pack`, ...) return OWNED
 *     handles the caller must `cm_value_destroy`.
 *   - `cm_invoke` arguments are BORROWED: the engine clones them, so the
 *     caller still owns its handles and destroys them after the call.
 *   - `cm_future_poll(future, &out)` hands a NEWLY OWNED handle to `out`.
 *   - Strings crossing to C (`cm_value_as_str`, `cm_value_to_string`,
 *     generated `_unpack` of `str` fields) are OWNED copies: free them
 *     with `cm_string_free`. `cm_value_str` / generated `_pack` COPY the
 *     bytes in, so a buffer handed to pack may be freed right after.
 *   - `cm_error_t` reports own their strings: `cm_error_free` after use.
 *     All `*_destroy` functions tolerate NULL.
 */

#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "cme.h"

/* ---------------------------------------------------------------------------
 * STEP 1: the generated scaffolding. `make` produces this header with
 * `cme codegen-c schemas/shop.cm` BEFORE compiling this file, so everything
 * below is checked against the schema at BUILD time:
 *   - Boundary types: `cme_shop_Item { int64_t id; char* sku; int64_t price }`
 *     and `cme_shop_OrderEvent` (a tagged union: `.variant` is one of
 *     `CME_shop_OrderEvent_Started / _Checkout`, payload lives in
 *     `.as.Checkout.total`). Note the enum tags keep the RAW namespace
 *     case (`CME_shop_...`), while the REGISTER macro below is UPPERCASE.
 *   - `cme_shop_Item_pack/unpack`, `cme_shop_OrderEvent_pack/unpack`: the
 *     typed data layer over the `cm_value_*` ABI.
 *   - `CME_SHOP_STORE_REGISTER(engine, user, fn_FetchItem, fn_RecordSale)`:
 *     registers the capability AND `_Static_assert`s each function against
 *     the schema signature. A wrong signature is a BUILD error, never a
 *     runtime surprise. A missing argument is a preprocessor error.
 *   - `cme_shop_checkout_OnOrder_invoke(ctx, arg0, &err)` /
 *     `cme_shop_checkout_TotalFor_invoke(ctx, arg0, &err)`: exact-arity
 *     host->script helpers. They take ONE `cm_value_t*` per schema param
 *     (pack scalars with `cm_value_int`, composites with `_pack`), and
 *     return an OWNED result value, or NULL with `out_error` filled.
 * ------------------------------------------------------------------------- */
#include "shop_schema_gen.h"

/* Host state for capability `shop.store`, threaded through the `user`
 * pointer given at registration. It must outlive the engine; a `main`-local
 * is fine because the engine is destroyed before `main` returns. Provider
 * functions may run on any invoking thread, so a real multithreaded host
 * would use atomics here — this demo stays single-threaded. */
struct ShopState {
    long next_id;
    long recorded_qty;
};

/* STEP 2a: provider for `Item FetchItem(str sku)`. The signature must match
 * `cm_capability_fn` EXACTLY (the REGISTER macro verifies it with
 * `_Generic`): borrowed `args`, owned return, NULL + `out_error` on failure.
 * `args[0]` is borrowed — valid for this call only, never stored. */
static cm_value_t *host_FetchItem(void *user, cm_value_t *const *args,
                                  size_t argc, cm_error_t *out_error) {
    struct ShopState *state = (struct ShopState *)user;
    if (argc != 1 || !args[0]) {
        if (out_error) out_error->kind = CM_ERROR_INVALID_ARG;
        return NULL;
    }
    /* `cm_value_as_str` hands an OWNED copy: free it before returning. */
    char *sku = NULL;
    if (cm_value_as_str(args[0], &sku, NULL) != CM_OK) {
        if (out_error) out_error->kind = CM_ERROR_INVALID_ARG;
        return NULL;
    }
    /* Fill the GENERATED struct and pack it. `_pack` copies the bytes in
     * (`cm_value_str` clones), so `sku` can be freed right after packing. */
    cme_shop_Item item;
    item.id = (int64_t)(state->next_id++);
    item.sku = sku;
    item.price = 42;
    cm_value_t *packed = cme_shop_Item_pack(&item);
    cm_string_free(sku);
    return packed; /* NULL on allocation failure: engine reports it. */
}

/* STEP 2b: provider for `void RecordSale(Item item, int qty)`. Void members
 * return `cm_value_void()`. The struct unpack ALSO yields owned strings:
 * `got.sku` must be freed even though we only read `qty`. */
static cm_value_t *host_RecordSale(void *user, cm_value_t *const *args,
                                   size_t argc, cm_error_t *out_error) {
    struct ShopState *state = (struct ShopState *)user;
    if (argc != 2 || !args[0] || !args[1]) {
        if (out_error) out_error->kind = CM_ERROR_INVALID_ARG;
        return NULL;
    }
    cme_shop_Item got;
    int64_t qty = 0;
    if (cme_shop_Item_unpack(args[0], &got) != CM_OK ||
        cm_value_as_int(args[1], &qty) != CM_OK) {
        cm_string_free(got.sku); /* unpack may have filled it already */
        if (out_error) out_error->kind = CM_ERROR_INVALID_ARG;
        return NULL;
    }
    state->recorded_qty = (long)qty;
    cm_string_free(got.sku);
    return cm_value_void();
}

/* Poll a just-invoked future to completion and hand back the owned result.
 * Today's engine resolves synchronously (CM_PENDING stays reserved for the
 * continuation-splitting VM), so one poll settles it. Returns NULL on
 * CM_ERROR after copying the report into `*err` for the caller to print. */
static cm_value_t *take_result(cm_future_t *future, cm_error_t *err) {
    cm_value_t *value = NULL;
    if (!future) return NULL;
    if (cm_future_poll(future, &value) == CM_ERROR) {
        if (err) *err = cm_future_get_error(future);
        cm_future_destroy(future);
        return NULL;
    }
    cm_future_destroy(future);
    return value;
}

static void print_error(const char *phase, const cm_error_t *err) {
    /* `file` names the owning module for mod builds (never virtual-text
     * coordinates); `line`/`column` are 0 when there is no position. */
    fprintf(stderr, "%s failed [kind=%d] %s:%d:%d: %s\n", phase, err->kind,
            err->file ? err->file : "", err->line, err->column,
            err->message ? err->message : "");
}

int main(int argc, char **argv) {
    const char *root = argc > 1 ? argv[1] : "shop_mod";
    int exit_code = 0;
    cm_error_t err = CM_ERROR_INIT;
    struct ShopState state;
    cm_engine_t *engine = NULL;
    cm_schema_t *schema = NULL;
    cm_program_t *program = NULL;
    cm_context_t *ctx = NULL;

    state.next_id = 1000;
    state.recorded_qty = 0;

    /* STEP 3: engine + schema registration. Parsing the SAME file the
     * header was generated from keeps one source of truth: the
     * compile-time asserts above and this runtime contract cannot drift
     * apart. The engine keeps its own copy, so the handle is destroyed
     * right after registering. */
    engine = cm_engine_new();
    if (!engine) {
        fprintf(stderr, "could not create the engine\n");
        return 2;
    }
    schema = cm_schema_parse_file("schemas/shop.cm", &err);
    if (!schema) {
        print_error("schema parse", &err);
        cm_error_free(&err);
        exit_code = 2;
        goto cleanup;
    }
    if (cm_engine_register_schema(engine, schema) != CM_OK) {
        fprintf(stderr, "schema registration rejected\n");
        exit_code = 2;
        goto cleanup;
    }
    cm_schema_destroy(schema);
    schema = NULL;

    /* STEP 4: wire the providers through the GENERATED macro. Order
     * matters: the provider-presence check runs at LOAD time, so this must
     * happen BEFORE `cm_engine_load_mod` below — a program calling an
     * unregistered capability fails to load, deterministically. */
    CME_SHOP_STORE_REGISTER(engine, &state, host_FetchItem, host_RecordSale);

    /* STEP 5: compile the MODULE, not a loose file. `cm_engine_load_mod`
     * reads mod.toml (whose `[schemas] shop = "1.0.0"` narrows the grant),
     * links src/main.cm + src/pricing.cm into ONE program (which is why
     * main.cm calls `priceFor` from pricing.cm with no import), and runs
     * the schema-gated check once. ANY diagnostic fails the load with
     * kind CM_ERROR_COMPILE; unchecked code never reaches a context. */
    program = cm_engine_load_mod(engine, root, &err);
    if (!program) {
        print_error("compile", &err);
        cm_error_free(&err);
        exit_code = 2;
        goto cleanup;
    }
    printf("loaded %smod with %d entries\n", cm_program_is_mod(program) ? "" : "non-",
           (int)cm_program_entry_count(program));

    /* STEP 6: execution context + §5.5 limits. NULL would select defaults;
     * here every invocation gets 1M fuel ops, a 5s wall clock, depth 64.
     * The context borrows the program (destroy context first) and
     * snapshots the registered providers. */
    {
        cm_limits_t limits = CM_LIMITS_INIT;
        limits.fuel = 1000000;
        limits.deadline_ms = 5000;
        limits.max_call_depth = 64;
        ctx = cm_engine_create_context(engine, program, &limits);
    }
    if (!ctx) {
        fprintf(stderr, "could not create the context\n");
        exit_code = 2;
        goto cleanup;
    }

    /* STEP 7a: script-calls-host. `main` runs FetchItem/RecordSale
     * (dispatched to the C providers above) plus the cross-file priceFor
     * helper: expected math is 42 (host price) + 3 * 10 = 72. */
    {
        cm_value_t *result = take_result(cm_invoke(ctx, NULL, "main", NULL, 0), &err);
        if (!result) {
            print_error("main", &err);
            cm_error_free(&err);
            exit_code = 1;
            goto cleanup;
        }
        int64_t total = 0;
        if (cm_value_as_int(result, &total) != CM_OK) {
            fprintf(stderr, "main returned a non-int\n");
            cm_value_destroy(result);
            exit_code = 1;
            goto cleanup;
        }
        printf("main -> %d\n", (int)total);
        cm_value_destroy(result);
    }

    /* STEP 7b: host-calls-script through the GENERATED exact-arity
     * helpers. The enum is packed C-side (variant tag + payload union) and
     * crosses the boundary typed: Checkout(21) + priceFor(2) = 41. */
    {
        cme_shop_OrderEvent event;
        event.variant = CME_shop_OrderEvent_Checkout;
        event.as.Checkout.total = 21;
        cm_value_t *event_value = cme_shop_OrderEvent_pack(&event);
        cm_value_t *points = NULL;
        int64_t scored = 0;
        if (!event_value) {
            fprintf(stderr, "Event pack failed\n");
            exit_code = 1;
            goto cleanup;
        }
        points = cme_shop_checkout_OnOrder_invoke(ctx, event_value, &err);
        cm_value_destroy(event_value); /* borrowed by the invoke: still ours */
        if (!points) {
            print_error("OnOrder", &err);
            cm_error_free(&err);
            exit_code = 1;
            goto cleanup;
        }
        if (cm_value_as_int(points, &scored) != CM_OK) {
            fprintf(stderr, "OnOrder returned a non-int\n");
            cm_value_destroy(points);
            exit_code = 1;
            goto cleanup;
        }
        printf("on_order(Checkout(21)) -> %d\n", (int)scored);
        cm_value_destroy(points);
    }

    /* Same helper shape for a scalar param: pack the int by hand, the
     * script's TotalFor runs priceFor(4) = 40. */
    {
        cm_value_t *qty = cm_value_int(4);
        cm_value_t *total_value = NULL;
        int64_t total = 0;
        if (!qty) {
            fprintf(stderr, "int pack failed\n");
            exit_code = 1;
            goto cleanup;
        }
        total_value = cme_shop_checkout_TotalFor_invoke(ctx, qty, &err);
        cm_value_destroy(qty);
        if (!total_value) {
            print_error("TotalFor", &err);
            cm_error_free(&err);
            exit_code = 1;
            goto cleanup;
        }
        if (cm_value_as_int(total_value, &total) != CM_OK) {
            fprintf(stderr, "TotalFor returned a non-int\n");
            cm_value_destroy(total_value);
            exit_code = 1;
            goto cleanup;
        }
        printf("total_for(4) -> %d\n", (int)total);
        cm_value_destroy(total_value);
    }

cleanup:
    /* Every destroy tolerates NULL, and reverse order keeps the
     * program-outlives-context contract. */
    cm_context_destroy(ctx);
    cm_program_destroy(program);
    if (schema) cm_schema_destroy(schema);
    cm_engine_destroy(engine);
    return exit_code;
}
