/* Generated by `cme codegen-c` from the `shop` schema — DO NOT EDIT.
  *
  * WHITEPAPER §9.6: the schema file is the single source of truth for
  * the script toolchain and the host bindings. This header is the C
  * half of that contract:
  *   - capability members: function-pointer types + a REGISTER macro
  *     whose _Static_asserts verify every host implementation's
  *     signature AT COMPILE TIME (a missing member fails the
  *     preprocessor, a wrong signature fails the assert);
  *   - interface members: typed invocation helpers with exact arity,
  *     so host call sites are compile-checked too;
  *   - schema structs/enums: pack/unpack helpers over the cm_value
  *     ABI (primitives, strs, and nested schema types; containers
  *     ride the stable cm_value accessors).
  *
  * One header per schema namespace (§9.2); several generated headers
  * may be included by one translation unit — the shared future
  * helper carries its own guard macro.
  */
#ifndef CME_SCHEMA_GEN_SHOP_H
#define CME_SCHEMA_GEN_SHOP_H

#include "cme.h"
#include <string.h> /* strcmp: enum unpack dispatches on the variant name */

/* schema shop v1.0.0 */
#define CME_SCHEMA_SHOP_VERSION "1.0.0"
#define CME_SCHEMA_SHOP_VERSION_MAJOR 1
#define CME_SCHEMA_SHOP_VERSION_MINOR 0
#define CME_SCHEMA_SHOP_VERSION_PATCH 0


/* Synchronously resolves an invocation future (the current engine
* completes synchronously; CM_PENDING stays reserved for the
* continuation-splitting VM, §4/§5.2). Guarded so several generated
* headers coexist in one translation unit. */
#ifndef CME_SCHEMA_GEN_FUTURE_TAKE_SYNC
#define CME_SCHEMA_GEN_FUTURE_TAKE_SYNC
static inline cm_value_t* cme_future_take_sync(cm_future_t* future, cm_error_t* out_error) {
    if (!future) {
        if (out_error) { out_error->kind = CM_ERROR_INVALID_ARG; }
        return NULL;
    }
    cm_poll_result_t result = cm_future_poll(future, NULL);
    if (result == CM_ERROR) {
        if (out_error) { *out_error = cm_future_get_error(future); }
        cm_future_destroy(future);
        return NULL;
    }
    cm_value_t* value = cm_future_take_value(future);
    cm_future_destroy(future);
    return value;
}
#endif /* CME_SCHEMA_GEN_FUTURE_TAKE_SYNC */


/* ---- schema struct cme_shop_Item (§9.3) ---- */
typedef struct cme_shop_Item {
    int64_t id;
    char* sku; /* owned after unpack: free with cm_string_free */
    int64_t price;
} cme_shop_Item;

/* Packs a host-side value into a script struct value; NULL on
* allocation failure. Fields not covered by the typed layer are
* attached with cm_struct_set_field by the caller. */
static inline cm_value_t* cme_shop_Item_pack(const cme_shop_Item* value) {
    if (!value) return NULL;
    cm_value_t* s = cm_value_struct("Item");
    if (!s) return NULL;
    { /* id */
        cm_value_t* f = cm_value_int(value->id);
        if (!f) goto fail;
        if (cm_struct_set_field(s, "id", f) != CM_OK) { cm_value_destroy(f); goto fail; }
    }
    { /* sku */
        cm_value_t* f = cm_value_str(value->sku);
        if (!f) goto fail;
        if (cm_struct_set_field(s, "sku", f) != CM_OK) { cm_value_destroy(f); goto fail; }
    }
    { /* price */
        cm_value_t* f = cm_value_int(value->price);
        if (!f) goto fail;
        if (cm_struct_set_field(s, "price", f) != CM_OK) { cm_value_destroy(f); goto fail; }
    }
    return s;
fail:
    cm_value_destroy(s);
    return NULL;
}

/* Unpacks a script struct value by field NAME; returns CM_OK,
* CM_ERR_KIND (wrong value kind), or CM_ERR_MISSING. `str` fields
* become OWNED copies — free them with cm_string_free. */
static inline cm_status_t cme_shop_Item_unpack(const cm_value_t* value, cme_shop_Item* out) {
    if (!value || cm_value_kind(value) != CM_VALUE_STRUCT) return CM_ERR_KIND;
    { /* id */
        const cm_value_t* f = cm_value_struct_field(value, "id");
        if (!f) return CM_ERR_MISSING;
        cm_status_t st = cm_value_as_int(f, &out->id);
        if (st != CM_OK) return st;
    }
    { /* sku: owned copy, free with cm_string_free */
        const cm_value_t* f = cm_value_struct_field(value, "sku");
        if (!f) return CM_ERR_MISSING;
        cm_status_t st = cm_value_as_str(f, &out->sku, NULL);
        if (st != CM_OK) return st;
    }
    { /* price */
        const cm_value_t* f = cm_value_struct_field(value, "price");
        if (!f) return CM_ERR_MISSING;
        cm_status_t st = cm_value_as_int(f, &out->price);
        if (st != CM_OK) return st;
    }
    return CM_OK;
}


/* ---- schema enum cme_shop_OrderEvent (§9.3): a tagged union over the cm_value
  * enum shape (name.variant + positional payload). Payload values
  * beyond the scalar layer ride the generic accessors; `str`
  * payloads unpack to OWNED copies (free with cm_string_free). ---- */
typedef enum {
    CME_shop_OrderEvent_Started = 0,
    CME_shop_OrderEvent_Checkout = 1,
} cme_shop_OrderEvent_tag;

typedef struct cme_shop_OrderEvent {
    cme_shop_OrderEvent_tag variant;
    union {
        struct { /* Started: 0 payload value(s) */
        } Started;
        struct { /* Checkout: 1 payload value(s) */
            int64_t total;
        } Checkout;

    } as;
} cme_shop_OrderEvent;

static inline cm_status_t cme_shop_OrderEvent_unpack(const cm_value_t* value, cme_shop_OrderEvent* out) {
    if (!value || cm_value_kind(value) != CM_VALUE_ENUM) return CM_ERR_KIND;
    char* variant_name = NULL;
    if (cm_value_enum_variant(value, &variant_name) != CM_OK || !variant_name) return CM_ERR_KIND;
    cm_status_t status = CM_ERR_KIND; /* stays set when no variant matches */
if (strcmp(variant_name, "Started") == 0) {
        status = CM_OK;
        if (cm_value_len(value) != 0) status = CM_ERR_MISSING;
        if (status == CM_OK) out->variant = CME_shop_OrderEvent_Started;
    }

else if (strcmp(variant_name, "Checkout") == 0) {
        status = CM_OK;
        if (cm_value_len(value) != 1) status = CM_ERR_MISSING;
            { cm_status_t st = CM_OK;
              const cm_value_t* p = cm_value_enum_payload(value, 0);
              if (!p) st = CM_ERR_MISSING;
              else st = cm_value_as_int(p, &out->as.Checkout.total);
              if (st != CM_OK && status == CM_OK) status = st; }
        if (status == CM_OK) out->variant = CME_shop_OrderEvent_Checkout;
    }

    cm_string_free(variant_name);
    return status;
}

/* Packs a typed value into a script enum value, pushing every
* typed payload (scalars, strs, nested schema types); NULL on
* failure. Container payloads attach with cm_enum_push by hand. */
static inline cm_value_t* cme_shop_OrderEvent_pack(const cme_shop_OrderEvent* value) {
    (void)value;
    switch (value->variant) {
    case CME_shop_OrderEvent_Started:
        {
            cm_value_t* e = cm_value_enum("OrderEvent", "Started");
            if (!e) return NULL;
            return e;
        }
    case CME_shop_OrderEvent_Checkout:
        {
            cm_value_t* e = cm_value_enum("OrderEvent", "Checkout");
            if (!e) return NULL;
        {
            cm_value_t* p = cm_value_int(value->as.Checkout.total);
            if (!p || cm_enum_push(e, p) != CM_OK) { cm_value_destroy(p); cm_value_destroy(e); return NULL; }
        }
            return e;
        }
    default:
        return NULL;
    }
}


/* ---- capability shop.store (§9.1): the script calls these; the host provides. ---- */
/* Schema member `shop.store.FetchItem` (since 1.0.0):
  *   Item FetchItem(str sku)
  * Arguments arrive positionally as cm_value_t* (borrowed, owned by
  * the engine); the provider returns a NEWLY OWNED cm_value_t* or
  * NULL with out_error filled. */
typedef cm_value_t* (*cme_shop_store_FetchItem_fn)(void* user, cm_value_t* const* args, size_t argc, cm_error_t* out_error);

/* Schema member `shop.store.RecordSale` (since 1.0.0):
  *   void RecordSale(Item item, int qty)
  * Arguments arrive positionally as cm_value_t* (borrowed, owned by
  * the engine); the provider returns a NEWLY OWNED cm_value_t* or
  * NULL with out_error filled. */
typedef cm_value_t* (*cme_shop_store_RecordSale_fn)(void* user, cm_value_t* const* args, size_t argc, cm_error_t* out_error);


typedef struct cme_shop_store_vtable {
    cme_shop_store_FetchItem_fn FetchItem;
    cme_shop_store_RecordSale_fn RecordSale;
} cme_shop_store_vtable_t;

/* Registers the capability with compile-time signature verification:
  * pass each member function by DESIGNATOR (or a correctly typed
  * pointer). A missing argument is a preprocessor error; a function
  * whose signature differs from the schema fails the _Static_assert. */
#define CME_SHOP_STORE_REGISTER(engine, user, \
            fn_FetchItem, \
            fn_RecordSale) \
    do { \
    _Static_assert(_Generic((fn_FetchItem), cme_shop_store_FetchItem_fn: 1, default: 0), \
        "shop.store.FetchItem: host function signature does not match the schema"); \
    _Static_assert(_Generic((fn_RecordSale), cme_shop_store_RecordSale_fn: 1, default: 0), \
        "shop.store.RecordSale: host function signature does not match the schema"); \
        const cm_capability_member_t cme_members_[] = { \
                { "FetchItem", fn_FetchItem }, \
                { "RecordSale", fn_RecordSale }, \
        }; \
        (void)cm_engine_register_capability((engine), "shop.store", cme_members_, 2, (user)); \
    } while (0)


/* ---- interface shop.checkout (§9.1): the script implements these; the host
  * calls in. `optional` members may be left unimplemented by the mod. ---- */
#define CME_SHOP_CHECKOUT_OnOrder_SINCE "1.0.0"
#define CME_SHOP_CHECKOUT_OnOrder_OPTIONAL 0
#define CME_SHOP_CHECKOUT_TotalFor_SINCE "1.0.0"
#define CME_SHOP_CHECKOUT_TotalFor_OPTIONAL 0

/* Calls the script's implementation of `shop.checkout.OnOrder` (since 1.0.0).
  * Exact arity: a call site passing the wrong number of values is a
  * COMPILE error. Returns an OWNED result value, or NULL with
  * out_error filled. */
static inline cm_value_t* cme_shop_checkout_OnOrder_invoke(
    cm_context_t* ctx, cm_value_t* arg0, cm_error_t* out_error) {
    cm_value_t* cme_args_[] = { arg0 };
    cm_future_t* future = cm_invoke(ctx, "shop.checkout", "OnOrder",
        cme_args_, 1);
    return cme_future_take_sync(future, out_error);
}

/* Calls the script's implementation of `shop.checkout.TotalFor` (since 1.0.0).
  * Exact arity: a call site passing the wrong number of values is a
  * COMPILE error. Returns an OWNED result value, or NULL with
  * out_error filled. */
static inline cm_value_t* cme_shop_checkout_TotalFor_invoke(
    cm_context_t* ctx, cm_value_t* arg0, cm_error_t* out_error) {
    cm_value_t* cme_args_[] = { arg0 };
    cm_future_t* future = cm_invoke(ctx, "shop.checkout", "TotalFor",
        cme_args_, 1);
    return cme_future_take_sync(future, out_error);
}



#endif /* CME_SCHEMA_GEN_SHOP_H */
